export const mockUser = {
  login: "mockuser",
  id: 12345,
  avatar_url: "https://ui-avatars.com/api/?name=Mock+User",
  url: "https://api.github.com/users/mockuser",
  name: "Mock User",
  company: "CommitIQ",
  blog: "https://commitiq.dev",
  location: "Internet",
  email: null,
  bio: "This is a mock user for fallback purposes when rate limits are hit.",
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 100,
  following: 50,
  created_at: "2020-01-01T00:00:00Z",
  updated_at: "2023-01-01T00:00:00Z"
};

export const mockRepos = [
  {
    id: 1,
    name: "mock-repo-1",
    full_name: "mockuser/mock-repo-1",
    private: false,
    owner: mockUser,
    html_url: "https://github.com/mockuser/mock-repo-1",
    description: "A mock repository",
    fork: false,
    url: "https://api.github.com/repos/mockuser/mock-repo-1",
    created_at: "2021-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
    pushed_at: "2023-01-01T00:00:00Z",
    stargazers_count: 10,
    watchers_count: 10,
    language: "JavaScript",
    forks_count: 2,
    open_issues_count: 1,
    license: { key: "mit", name: "MIT License" },
    topics: ["react", "nodejs"],
    visibility: "public"
  },
  {
    id: 2,
    name: "mock-repo-2",
    full_name: "mockuser/mock-repo-2",
    private: false,
    owner: mockUser,
    html_url: "https://github.com/mockuser/mock-repo-2",
    description: "Another mock repository",
    fork: false,
    url: "https://api.github.com/repos/mockuser/mock-repo-2",
    created_at: "2021-02-01T00:00:00Z",
    updated_at: "2023-02-01T00:00:00Z",
    pushed_at: "2023-02-01T00:00:00Z",
    stargazers_count: 5,
    watchers_count: 5,
    language: "TypeScript",
    forks_count: 0,
    open_issues_count: 0,
    license: null,
    topics: [],
    visibility: "public"
  }
];
